version: "3"
# unfortunatelly build from docker-compose.yml does not supported by Fly.io, 
# but for future let's keep it there.

services:
  service1:
    container_name: workshop_azati_service
    restart: always
    build:
      context: .
    ports:
      - "3000:5000"