name: Deploy to Fly.io

on:
  push:
    branches:
      - gh-actions

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh

      - name: Deploy to Fly.io
        run: flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
