name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Fly CLI
        run: |
          curl -L https://fly.io/install.sh | sh
          echo 'export PATH="$HOME/.fly/bin:$PATH"' >> $HOME/.bashrc
          source $HOME/.bashrc

      - name: Deploy to Fly.io
        run: |
          flyctl deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
